# Generated by Django 6.0.3 on 2026-03-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_avatar_customuser_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(choices=[('presidente', 'Presidente'), ('diretor', 'Diretor'), ('gerente', 'Gerente'), ('supervisor', 'Supervisor'), ('operador', 'Operador')], default='operador', max_length=20),
        ),
    ]
