# Generated by Django 6.0.3 on 2026-03-15 12:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cor_identificadora',
            field=colorfield.fields.ColorField(default='#6c757d', help_text='Cor do Kanban', image_field=None, max_length=25, samples=None),
        ),
    ]
