# Generated by Django 6.0.3 on 2026-03-15 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desenvolvimento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagem_cad',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/cad/'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='quantidade_figuras',
            field=models.PositiveIntegerField(default=1, verbose_name='Figuras no Molde'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='responsavel_proxima_fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_a_assumir', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projeto',
            name='sobremetal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sobremetal (mm)'),
        ),
    ]
