# Generated by Django 6.0.3 on 2026-03-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desenvolvimento', '0002_projeto_imagem_cad_projeto_observacoes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='ultima_atualização',
            new_name='ultima_atualizacao',
        ),
    ]
